[recon]
tracking_ids = [0,1,2,3,4,5]
num_points_min = 5
search_spatial_sigma_max = 50.0
extrapolation_ids = [0,1,2,3,4,5,6,7,8]
track_fitter = "straight3d"

[recon.gbl3d]
tracking_ids = [0,1,2,3,4,5]
extrapolation_ids = [0,1,2,3,4,5,6,7,8]
search_spatial_sigma_max = 10.0
# disable search cut in time
search_temporal_sigma_max = -1.0
num_points_min = 5
track_fitter = "gbl3d"

[recon.straight4d]
tracking_ids = [0,1,2,3,4,5]
num_points_min = 5
search_spatial_sigma_max = 10.0
extrapolation_ids = [0,1,2,3,4,5,6,7,8]
track_fitter = "straight4d"
