name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - run: echo "starting my own workflow"
        - run: pwd
        - uses: actions/checkout@v3
        - run: 'ls -a ../HighResAnalysis'
        - run: 'ls -a '
        - run: conda init bash
        - run: conda config --set channel_priority strict
        - run: conda create -c conda-forge --name test root
        - run: conda activate test
        - run: 'which root'
        - uses: fastai/workflows/quarto-ghp@master
