name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - run: echo "starting my own workflow"
        - run: conda install -c conda-forge root
        - uses: fastai/workflows/quarto-ghp@master
