name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
        - run: echo "starting my own workflow"
        - run: pwd
        - uses: actions/checkout@v3
        - run: 'ls -a ../HighResAnalysis'
        - run: 'ls -a '
        #- name: provision-with-micromamba
        # You may pin to the exact commit or the version.
        # uses: mamba-org/provision-with-micromamba@e2b397b12d0a38069451664382b769c9456e3d6d
        - name: Install Conda environment from environment.yml
          uses: mamba-org/provision-with-micromamba@main
        - run: micromamba activate testenv
        - run: 'which root'
        - run: python -c 'import ROOT'
        - name: publish with quarto
          uses: fastai/workflows/quarto-ghp@master
          with:
            version: 3.10
