name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - run: echo "starting my own workflow"
        - run: pwd
        - uses: actions/checkout@v3
        - run: 'ls -a ../HighResAnalysis'
        - run: 'ls -a '
        - run: sudo snap install root-framework
        - run: snap run root-framework
        - run: 'which root'
        - uses: fastai/workflows/quarto-ghp@master
