name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
        - run: echo "starting my own workflow"
        - run: pwd
        - uses: actions/checkout@v3
        - run: 'ls -a ../HighResAnalysis'
        - run: 'ls -a '
        #- name: provision-with-micromamba
        # You may pin to the exact commit or the version.
        # uses: mamba-org/provision-with-micromamba@e2b397b12d0a38069451664382b769c9456e3d6d
        - name: Install Conda environment from environment.yml
          uses: mamba-org/provision-with-micromamba@main
        - run: micromamba activate testenv
        - run: 'which root'
        - run: python -c 'import ROOT'
        - name: Install Dependencies
          env: 
            USE_PRE: ''
          run: |
           set -ux
           python -m pip install --upgrade pip
           if [ $USE_PRE ]; then
             pip install -Uq git+https://github.com/fastai/ghapi.git
             pip install -Uq git+https://github.com/fastai/fastcore.git
             pip install -Uq git+https://github.com/fastai/execnb.git
             pip install -Uq git+https://github.com/fastai/nbdev.git
             wget -q $(curl https://latest.fast.ai/pre/quarto-dev/quarto-cli/linux-amd64.deb)
             sudo dpkg -i quarto*.deb
           else
             pip install -Uq nbdev
           fi
           test -f setup.py && pip install -e ".[dev]"
           nbdev_docs
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ inputs.ghtoken }}
            force_orphan: true
            publish_dir: ./_docs
            # The following lines assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch.
           #  You can swap them out with your own user credentials.
            user_name: github-actions[bot]
            user_email: 41898282+github-actions[bot]@users.noreply.github.com
#           uses: fastai/workflows/quarto-ghp@master
#           with:
#             version: '3.10'
